---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: debian-7.7.0-amd64
  driver_config:
    box: debian-7.7.0-amd64
    box_url: https://vagrantcloud.com/ffuenf/boxes/debian-7.7.0-amd64/versions/2/providers/virtualbox.box

- name: ubuntu-14.04.1-server-amd64
  driver_config:
    box: ubuntu-14.04.1-server-amd64
    box_url: https://vagrantcloud.com/ffuenf/boxes/ubuntu-14.04.1-server-amd64/versions/12/providers/virtualbox.box

suites:
- name: default
  data_bags_path: test/integration/default/data_bags
  encrypted_data_bag_secret_key_path: .data_bags/insecure_databag_secret
  run_list:
    - recipe[dop_datadog::default]
  attributes: {}